### ISSUE TITLE
Blogs gone

### ISSUE THREAD

**Issue by matozoid** [WardCunningham/Txtzyme#10]
Hi! I wanted to check out your blogs (linked in the readme), but the whole domain is gone.

**Comment by WardCunningham** [comment]
Must be a problem on your end.

![image](https://user-images.githubusercontent.com/12127/59363988-fc060680-8cea-11e9-9675-98110ddb77e3.png)

**Comment by matozoid** [comment]
I mean these two:

    http://dorkbotpdx.org/blog/wardcunningham/shell_programming_with_txtzyme
    http://dorkbotpdx.org/blog/wardcunningham/plotting_signals_with_txtzyme

**Comment by WardCunningham** [comment]
Google found these copies. If you would like to make copies of your own you can fork them into federated wiki from here. 

http://txtzyme.com/shell-programming-with-txtzyme.html
http://txtzyme.com/view/plotting-signals-with-txtzyme

**Comment by matozoid** [comment]
Ok thanks. I've posted the issue to notify you there are broken links in your readme, so that you can fix them.

**Comment by WardCunningham** [comment]
I'll wait for the dorkbotpdx web crew to get their site back up.

**Comment by matozoid** [comment]
Thanks for the links, by the way :-)
